version: "3"
services:
  database:
    image: postgres:latest
    container_name: "database"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    
  backend:
    build: ./server
    container_name: backend
    image: python:3.11.1
    restart: always
    command: gunicorn "app:create_app()" -b 0.0.0.0:8888
    ports:
      - "8888:8888"
  
  frontend:
    build: ./client/frontend
    image: node:19.0.0
    container_name: "frontend"
    restart: always
    environment:
      PROD_PORT: ${PROD_PORT}
    ports:
      - "${PROD_PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./client/frontend:/app
    depends_on:
      - backend
      